config/routes.rb
Rails.application.routes.draw do
  resources :offers, only: :index
  root 'offers#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    if params[:uid]
      offer_service = OfferService.new params[:uid], pub0: params[:pub0], page: params[:page]
      service_response = offer_service.get
      @offers = JSON.parse(service_response.body)['offers']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>FyberChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/offers/index.html.slim
h1 Offers

= form_tag offers_path, method: :get
  .form-group
    = label_tag :uid
    = text_field_tag :uid, '', class: 'form-control'
  .form-group
    = label_tag :pub0
    = text_field_tag :pub0, '', class: 'form-control'
  .form-group
    = label_tag :page
    = text_field_tag :page, '', class: 'form-control', type: :number
  = submit_tag 'Show offers', class: 'btn btn-default'

- if @offers && @offers.any?
  - @offers.each do |offer|
    .offer
      .title = offer['title']
      .payout = offer['payout']
      .thumbnail = image_tag offer['thumbnail']['lowres']
- else
  .no_offers No offers